---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-symlinks
      # - id: check-xml
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.14.0
    hooks:
      - id: gitlint
        name: Check Git rules via gitlint
        args: [-v, --ignore=body-is-missing, --msg-filename]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.26.2
    hooks:
      - id: yamllint
        name: Yaml validate with yamllint
        args: [-c=.yamllint-config.yaml]

  - repo: https://github.com/willthames/ansible-lint.git
    rev: v4.3.6
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.50.0
    hooks:
      - id: terraform_fmt
      - id: terraform_tflint
      - id: terraform_validate

  - repo: https://github.com/motet-a/jinjalint
    rev: 01e0a4d8
    hooks:
      - id: jinjalint
        name: Jinja validate with jinjalint
        types: [file]
        files: \.(j2)$